### ISSUE TITLE
Build samples are obsolete - readme should be updated to provide a pointer to the new location

### ISSUE THREAD

**Issue by counsellorben** [Azure/servicefabric-samples#27]
Downloaded the samples, set up my environment, upgraded VS 2015 to Azure 2.8.

None of the VS 2015 samples will load.  I get a message that the sfproj file must be upgraded in order to be loaded.  I click Yes, then get an error message Object reference not set to instance of object.

Net result, unable to load any of the samples.

**Comment by seanmck** [comment]
This repo is obsolete and will be soon be removed (I will add this to readme today). Going forward, you can find all Service Fabric samples in the [Azure samples gallery](http://aka.ms/servicefabricsamples). The simplest ones are available in the [Getting Started repo](https://azure.microsoft.com/en-us/documentation/samples/service-fabric-dotnet-getting-started/).

**Comment by counsellorben** [comment]
Thanks for the quick response.

**Comment by seanmck** [comment]
Readme updated.
